[tasks.build-docker-images]
dependencies = [
    "build-data-collector-docker",
	"build-data-forwarder-musl",
	"build-bundler-audit-docker"
]

[tasks.build-data-collector-docker]
command = "cargo"
args = ["make", "--cwd", "data-collector", "build-data-collector-docker"]

[tasks.build-data-forwarder-musl]
command = "cargo"
args = ["make", "--cwd", "data-forwarder", "build-data-forwarder-musl"]

[tasks.build-bundler-audit-docker]
command = "cargo"
args = ["make", "--cwd", "tool-images/ruby/bundler-audit", "build-bundler-audit-docker"]
