[package]
name = "kiln_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
avro-rs = "0.6"
chrono = { version = "0.4", features = ["serde"] }
actix-web = "1.0"
http = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.0"
failure = "0.1"
