[package]
name = "kiln_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
avro-rs = { version = "0.6", optional = true }
chrono = { version = "0.4", features = ["serde"] }
actix-web = { version = "1.0", optional = true }
http = { version = "0.1", optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
regex = "1.0"
failure = "0.1"
rdkafka = { version = "0.23", optional = true, features = ["cmake-build", "ssl-vendored"] }
addr = { version = "0.2", optional = true }
url = "2.1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[features]

default = []
all = ["avro", "web", "json", "streaming"]
avro = ["avro-rs"]
json = ["serde_json"]
web = ["actix-web", "http", "json"]
streaming = ["addr", "rdkafka"]
