[package]
name = "kiln_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
lambda_http = "0.1"
http = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.0"

[dev-dependencies]
avro-rs = "0.6"
