[tasks.build-kiln-cli]
dependencies = [
	"kiln-cli-build", 
	"copy-binary-to-root-dir",
]

[tasks.kiln-cli-build]
script = [
	"cargo build --release"
] 

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 cargo build --release"
]

[tasks.copy-binary-to-root-dir]
script = [
	"mkdir -p ../bin && cp ./target/release/kiln-cli ../bin"
] 

