[tasks.build-kiln-cli]
dependencies = [
	"kiln-cli-build", 
	"copy-binary-to-root-dir",
]

[tasks.kiln-cli-build]
script = [
	"cargo build --release"
] 

[tasks.rpm]
dependencies = [
	"build-rpm-builder",
	"musl-build",
	"build-rpm",
	"move-rpm"
]

[tasks.build-rpm]
script = [
	"../utils/rpm-builder/target/release/rpm-builder --exec-file target/x86_64-unknown-linux-musl/release/kiln-cli:/usr/bin/kiln-cli --compression gzip --arch x86_64 --desc 'CLI Tool for running security tools to send data to a Kiln stack' --license MIT --version $CARGO_MAKE_CRATE_VERSION kiln-cli-$CARGO_MAKE_CRATE_VERSION.x86_64",
]

[tasks.move-rpm]
script  = [
	"mkdir -p target/rpm",
	"mv *.rpm target/rpm/"
]

[tasks.build-rpm-builder]
script = [
	"cd ../utils/rpm-builder/",
	"cargo build --release"
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable cargo build --release"
]

[tasks.copy-binary-to-root-dir]
script = [
	"mkdir -p ../bin && cp ./target/release/kiln-cli ../bin"
] 

