[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.build-report-parser]
dependencies = [
    "clippy",
	"test",
	"build",
]

[tasks.build-report-parser-docker]
dependencies = [
	"musl-build",
	"build-report-parser-docker-image",
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable sudo chown -R rust:rust /opt/rust/cargo/git /opt/rust/cargo/registry /home/rust/src/target",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable cargo build --release"
]

[tasks.build-report-parser-docker-image]
command = "docker"
args = ["build", "-t", "kiln/report-parser:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-report-parser-git-docker]
dependencies = ["musl-build", "build-report-parser-docker-tag-git-version", "build-report-parser-docker-tag-git-latest"]

[tasks.build-report-parser-docker-tag-git-version]
command = "docker"
args = ["build", "-t", "kiln/report-parser:git-${GIT_SHA}", "."]

[tasks.push-report-parser-docker-git-version]
command = "docker"
args = ["push", "kiln/report-parser:git-${GIT_SHA}"]

[tasks.build-report-parser-docker-tag-git-latest]
command = "docker"
args = ["tag", "kiln/report-parser:git-${GIT_SHA}", "kiln/report-parser:git-latest"]

[tasks.push-report-parser-docker-git-latest]
command = "docker"
args = ["push", "kiln/report-parser:git-latest"]

[tasks.build-report-parser-release-docker]
dependencies = ["musl-build", "build-report-parser-docker-tag-release-version", "build-report-parser-docker-tag-release-latest"]

[tasks.build-report-parser-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/report-parser:$GIT_TAG ."
]

[tasks.push-report-parser-docker-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/report-parser:$GIT_TAG ."
]

[tasks.build-report-parser-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/report-parser:$GIT_TAG kiln/report-parser:latest"
]

[tasks.push-report-parser-docker-release-latest]
script = [
	"docker push kiln/report-parser:latest"
]
