[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.build-report-parser]
dependencies = [
    "clippy",
	"test",
	"build",
]

[tasks.build-report-parser-docker]
dependencies = [
	"musl-build",
	"build-report-parser-docker-image",
]

[tasks.musl-build]
script = [
	"docker run --rm -it -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry -v target:/home/rust/src/target ekidd/rust-musl-builder:stable-openssl11 sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -it -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry -v target:/home/rust/src/target ekidd/rust-musl-builder:stable-openssl11 cargo build --release"
]

[tasks.build-report-parser-docker-image]
command = "docker"
args = ["build", "-t", "kiln/report-parser:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-report-parser-master-docker]
dependencies = ["musl-build", "build-report-parser-docker-tag-master-version", "build-report-parser-docker-tag-master-latest"]

[tasks.build-report-parser-docker-tag-master-version]
command = "docker"
args = ["build", "-t", "kiln/report-parser:master-${GIT_SHA}", "."]

[tasks.push-report-parser-docker-master-version]
command = "docker"
args = ["push", "kiln/report-parser:master-${GIT_SHA}"]

[tasks.build-report-parser-docker-tag-master-latest]
command = "docker"
args = ["tag", "kiln/report-parser:master-${GIT_SHA}", "kiln/report-parser:master-latest"]

[tasks.push-report-parser-docker-master-latest]
command = "docker"
args = ["push", "kiln/report-parser:master-latest"]

[tasks.build-report-parser-release-docker]
dependencies = ["musl-build", "build-report-parser-docker-tag-release-version", "build-report-parser-docker-tag-release-latest"]

[tasks.build-report-parser-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/report-parser:$GIT_TAG ."
]

[tasks.push-report-parser-docker-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/report-parser:$GIT_TAG ."
]

[tasks.build-report-parser-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/report-parser:$GIT_TAG kiln/report-parser:latest"
]

[tasks.push-report-parser-docker-release-latest]
script = [
	"docker push kiln/report-parser:latest"
]
