[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.build-slack-connector]
dependencies = [
    "clippy",
	"test",
	"build",
]

[tasks.build-slack-connector-docker]
dependencies = [
	"musl-build",
	"build-slack-connector-docker-image",
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 cargo build --release"
]

[tasks.build-slack-connector-docker-image]
command = "docker"
args = ["build", "-t", "kiln/slack-connector:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-slack-connector-master-docker]
dependencies = ["musl-build", "build-slack-connector-docker-tag-master-version", "build-slack-connector-docker-tag-master-latest"]

[tasks.build-slack-connector-docker-tag-master-version]
command = "docker"
args = ["build", "-t", "kiln/slack-connector:master-${GIT_SHA}", "."]

[tasks.push-slack-connector-docker-master-version]
command = "docker"
args = ["push", "kiln/slack-connector:master-${GIT_SHA}"]

[tasks.build-slack-connector-docker-tag-master-latest]
command = "docker"
args = ["tag", "kiln/slack-connector:master-${GIT_SHA}", "kiln/slack-connector:master-latest"]

[tasks.push-slack-connector-docker-master-latest]
command = "docker"
args = ["push", "kiln/slack-connector:master-latest"]

[tasks.build-slack-connector-release-docker]
dependencies = ["musl-build", "build-slack-connector-docker-tag-release-version", "build-slack-connector-docker-tag-release-latest"]

[tasks.build-slack-connector-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/slack-connector:$GIT_TAG ."
]

[tasks.push-slack-connector-docker-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/slack-connector:$GIT_TAG ."
]

[tasks.build-slack-connector-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/slack-connector:$GIT_TAG kiln/slack-connector:latest"
]

[tasks.push-slack-connector-docker-release-latest]
script = [
	"docker push kiln/slack-connector:latest"
]
