{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}-exporter
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9141
      targetPort: metrics
  selector: {{- include "zookeeper.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
{{- end }}
