[tasks.build-data-forwarder]
dependencies = [
	"build",
    "clippy",
]

[tasks.build-data-forwarder-musl]
dependencies = [
	"musl-build", 
	"copy-binary-to-root-dir",
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable sudo chown -R rust:rust /opt/rust/cargo/git /opt/rust/cargo/registry /home/rust/src/target",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable cargo build --release"
] 

[tasks.copy-binary-to-root-dir]
script = [
	"mkdir -p ../bin && cp ./target/x86_64-unknown-linux-musl/release/data-forwarder ../bin"
] 

