[tasks.build-data-forwarder]
dependencies = [
    "clippy",
	"test",
	"musl-build",
]

[tasks.musl-build]
script = [
	"docker run --rm -it -v $PWD:/workdir -v ~/.cargo/git:/root/.cargo/git -v ~/.cargo/registry:/root/.cargo/registry registry.gitlab.com/rust_musl_docker/image:stable-latest cargo build --release --target=x86_64-unknown-linux-musl"
]
