[tasks.build-data-forwarder]
dependencies = [
	"build",
    "clippy",
]

[tasks.build-data-forwarder-musl]
dependencies = [
	"musl-build", 
	"copy-binary-to-root-dir",
]

[tasks.musl-build]
script = [
	"docker run --rm -it -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -it -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 cargo build --release"
] 

[tasks.copy-binary-to-root-dir]
script = [
	"mkdir -p ../bin && cp ./target/x86_64-unknown-linux-musl/release/data-forwarder ../bin"
] 

