[tasks.build-data-forwarder]
dependencies = [
	"build",
    "clippy",
]

[tasks.build-data-forwarder-musl]
dependencies = [
	"musl-build", 
	"copy-binary-to-root-dir",
]

[tasks.musl-build]
script = [
	"docker run --rm -v $PWD:/workdir -v ~/.cargo/git:/root/.cargo/git -v ~/.cargo/registry:/root/.cargo/registry registry.gitlab.com/rust_musl_docker/image:stable-latest cargo build --release --target=x86_64-unknown-linux-musl"
] 

[tasks.copy-binary-to-root-dir]
script = [
	"mkdir -p ../bin && cp ./target/x86_64-unknown-linux-musl/release/data-forwarder ../bin"
] 

