{{- if .Values.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zookeeper.fullname" . }}-exporter
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "zookeeper.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  template:
    metadata:
      {{- if .Values.metrics.podAnnotations }}
      annotations: {{- toYaml .Values.metrics.podAnnotations | nindent 8 }}
      {{- end }}
      labels: {{- include "zookeeper.labels" . | nindent 8 }}
      {{- if .Values.metrics.podLabels }}
      {{- toYaml .Values.metrics.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- include "zookeeper.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.metrics.affinity }}
      affinity: {{- include "zookeeper.tplValue" (dict "value" .Values.metrics.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.nodeSelector }}
      nodeSelector: {{- include "zookeeper.tplValue" (dict "value" .Values.metrics.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.tolerations }}
      tolerations: {{- include "zookeeper.tplValue" (dict "value" .Values.metrics.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ template "zookeeper.metrics.image" . }}
          name: zookeeper-exporter
          command:
            - /usr/local/bin/zookeeper-exporter
            - -timeout
            - {{ .Values.metrics.timeoutSeconds | quote }}
            - -zk-list
            {{- $replicaCount := int .Values.replicaCount }}
            {{- $followerPort := int .Values.service.followerPort }}
            {{- $electionPort := int .Values.service.electionPort }}
            {{- $servicePort := int .Values.service.port }}
            {{- $releaseNamespace := .Release.Namespace }}
            {{- $zookeeperFullname := include "zookeeper.fullname" . }}
            {{- $zookeeperHeadlessServiceName := printf "%s-%s" $zookeeperFullname "headless" | trunc 63  }}
            {{- $clusterDomain := .Values.clusterDomain }}
            - {{range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}:{{ $servicePort }}{{- if (lt $e ( sub $replicaCount 1)) -}},{{- end -}}{{ end }}
          ports:
            - name: metrics
              containerPort: 8080
          {{- if .Values.metrics.resources }}
          resources: {{- toYaml .Values.metrics.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
{{- end }}
