proxy:
  secretToken: ""
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: kiln-jupyterhub.my-subdomain.mydomain.tld
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  https:
    enabled: true
    type: offload
singleuser:
  image:
    name: "danielmurphy/pyspark-notebook"
    tag: "3.0.0-preview2-3"
    pullPolicy: "IfNotPresent"
    memory:
      limit: 28G
      guarantee: 28G
    cpu:
      limit: 7
      guarantee: 7
scheduling:
  userPods:
    nodeAffinity:
      matchNodePurpose: require

auth:
  type: github
  github:
    clientId: ""
    clientSecret: ""
    callbackUrl: "https://kiln-jupyterhub.my-subdomain.mydomain.tld/hub/oauth_callback"
  admin:
    access: true
    users:
      - ""
