[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.pre-build-safety-docker]
command = "cp"
args = ["../../../bin/data-forwarder", "data-forwarder"]

[tasks.post-build-safety-docker]
command = "rm"
args = ["data-forwarder"]

[tasks.build-safety-docker]
dependencies = ["pre-build-safety-docker"]
command = "docker"
args = ["build", "-t", "kiln/safety:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-safety-git-docker]
dependencies = ["build-safety-docker-tag-git-version", "build-safety-docker-tag-git-latest"]

[tasks.build-safety-docker-tag-git-version]
command = "docker"
args = ["build", "-t", "kiln/safety:git-${GIT_SHA}", "."]

[tasks.safety-docker-push-git-version]
command = "docker"
args = ["push", "kiln/safety:git-${GIT_SHA}"]

[tasks.build-safety-docker-tag-git-latest]
command = "docker"
args = ["tag", "kiln/safety:git-${GIT_SHA}", "kiln/safety:git-latest"]

[tasks.safety-docker-push-git-latest]
command = "docker"
args = ["push", "kiln/safety:git-latest"]

[tasks.build-safety-release-docker]
dependencies = ["build-safety-docker-tag-release-version", "build-safety-docker-tag-release-latest"]

[tasks.build-safety-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/safety:$GIT_TAG ."
]

[tasks.safety-docker-push-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/safety:$GIT_TAG"
]

[tasks.build-safety-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/safety:$GIT_TAG kiln/safety:latest"
]

[tasks.safety-docker-push-release-latest]
command = "docker"
args = ["push", "kiln/safety:latest"]
