apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  selector:
    matchLabels: {{- include "kafka.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
  serviceName: {{ template "kafka.fullname" . }}-headless
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: {{ .Values.updateStrategy | quote }}
    {{- if (eq "Recreate" .Values.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      labels: {{- include "kafka.labels" . | nindent 8 }}
        app.kubernetes.io/component: kafka
    spec:
{{- include "kafka.imagePullSecrets" . | indent 6 }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      nodeSelector: {{- include "kafka.tplValue" ( dict "value" .Values.nodeSelector "context" $ ) | nindent 8 }}
      tolerations: {{- include "kafka.tplValue" ( dict "value" .Values.tolerations "context" $ ) | nindent 8 }}
      affinity: {{- include "kafka.tplValue" ( dict "value" .Values.affinity "context" $ ) | nindent 8 }}
      {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
      initContainers:
        - name: volume-permissions
          image: {{ include "kafka.volumePermissions.image" . }}
          imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "/bitnami/kafka"]
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          resources: {{ toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: "/bitnami/kafka"
      {{- end }}
      containers:
        - name: kafka
          image: {{ include "kafka.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.image.debug | quote }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              {{- if .Values.zookeeper.enabled }}
              value: {{ template "kafka.zookeeper.fullname" . }}
              {{- else }}
              value: {{ .Values.externalZookeeper.servers | quote }}
              {{- end }}
            - name: KAFKA_PORT_NUMBER
              value: {{ .Values.service.port | quote }}
            - name: KAFKA_CFG_LISTENERS
              {{- if .Values.listeners }}
              value: {{ .Values.listeners }}
              {{- else if and .Values.auth.ssl .Values.auth.enabled }}
              value: "SASL_SSL://:$(KAFKA_PORT_NUMBER),SSL://:9093"
              {{- else if .Values.auth.enabled }}
              value: "SASL_SSL://:$(KAFKA_PORT_NUMBER)"
              {{- else if and .Values.auth.ssl .Values.allowPlaintextListener }}
              value: "SSL://:9093,PLAINTEXT://:$(KAFKA_PORT)"
              {{- else if .Values.auth.ssl }}
              value: "SSL://:9093"
              {{- else }}
              value: "PLAINTEXT://:$(KAFKA_PORT_NUMBER)"
              {{- end }}
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              {{- if .Values.advertisedListeners }}
              value: {{ .Values.advertisedListeners }}
              {{- else if and .Values.auth.ssl .Values.auth.enabled }}
              value: 'SASL_SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:$(KAFKA_PORT_NUMBER),SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:9093'
              {{- else if .Values.auth.enabled  }}
              value: 'SASL_SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:$(KAFKA_PORT_NUMBER)'
              {{- else if and .Values.auth.ssl .Values.allowPlaintextListener}}
              value: 'PLAINTEXT://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:$(KAFKA_PORT_NUMBER),SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:9093'
              {{- else if .Values.auth.ssl }}
              value: 'SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:9093'
              {{- else }}
              value: 'PLAINTEXT://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.{{.Release.Namespace}}.svc.{{ .Values.clusterDomain }}:$(KAFKA_PORT_NUMBER)'
              {{- end }}
            {{- if .Values.auth.ssl }}
            - name: KAFKA_CFG_SSL_ENABLED_PROTOCOLS
              value: "TLSv1.2"
            - name: KAFKA_CFG_SSL_PROTOCOL
              value: "TLSv1.2"
            - name: KAFKA_CFG_SSL_CIPHER_SUITES
              value: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
            - name: KAFKA_CFG_SSL_KEYSTORE_LOCATION
              value: "/opt/bitnami/kafka/conf/certs/kafka.keystore.jks"
            - name: KAFKA_CFG_SSL_TRUSTSTORE_LOCATION
              value: "/opt/bitnami/kafka/conf/certs/kafka.truststore.jks"
            {{- end }}
            {{- if .Values.auth.certificatesPassword }}
            - name: KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD
              value: {{ .Values.auth.certificatesPassword | quote }}
            - name: KAFKA_CFG_SSL_KEYSTORE_PASSWORD
              value: {{ .Values.auth.certificatesPassword | quote }}
            {{- end }}
            {{- if .Values.listenerSecurityProtocolMap }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.listenerSecurityProtocolMap }}
            {{- end }}
            {{- if .Values.interBrokerListenerName }}
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: {{ .Values.interBrokerListenerName }}
            {{- end }}
            {{- if .Values.metrics.jmx.enabled }}
            - name: JMX_PORT
              value: {{ .Values.metrics.jmx.jmxPort | quote }}
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"
            - name: KAFKA_BROKER_USER
              value: {{ .Values.auth.brokerUser | quote }}
            - name: KAFKA_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ template "kafka.fullname" . }}{{ end }}
                  key: kafka-broker-password
            - name: KAFKA_INTER_BROKER_USER
              value: {{ .Values.auth.interBrokerUser | quote }}
            - name: KAFKA_INTER_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ template "kafka.fullname" . }}{{ end }}
                  key: kafka-inter-broker-password
            {{- if .Values.auth.zookeeperUser }}
            - name: KAFKA_ZOOKEEPER_USER
              value: {{ .Values.auth.zookeeperUser | quote }}
            {{- end }}
            {{- if .Values.auth.zookeeperPassword }}
            - name: KAFKA_ZOOKEEPER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ template "kafka.fullname" . }}{{ end }}
                  key: kafka-zookeeper-password
            {{- end }}
            {{- end }}
            {{- if .Values.auth.certificatesPassword }}
            - name: KAFKA_CERTIFICATE_PASSWORD
              value: {{ .Values.auth.certificatesPassword | quote }}
            {{- end }}
            - name: ALLOW_PLAINTEXT_LISTENER
              value: {{ ternary "yes" "no" (or .Values.auth.enabled .Values.allowPlaintextListener) | quote }}
            - name: KAFKA_CFG_BROKER_ID
              value: {{ .Values.brokerId | quote }}
            - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
              value: {{ .Values.deleteTopicEnable | quote }}
            - name: KAFKA_HEAP_OPTS
              value: {{ .Values.heapOpts | quote }}
            - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
              value: {{ .Values.logFlushIntervalMessages | quote }}
            - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MS
              value: {{ .Values.logFlushIntervalMs | quote }}
            - name: KAFKA_CFG_LOG_RETENTION_BYTES
              value: {{ .Values.logRetentionBytes | replace "_" "" | quote }}
            - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS
              value: {{ .Values.logRetentionCheckIntervalMs | quote }}
            - name: KAFKA_CFG_LOG_RETENTION_HOURS
              value: {{ .Values.logRetentionHours | quote }}
            {{- if .Values.logMessageFormatVersion }}
            - name: KAFKA_CFG_LOG_MESSAGE_FORMAT_VERSION
              value: {{ .Values.logMessageFormatVersion | quote }}
            {{- end }}
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: {{ .Values.maxMessageBytes | replace "_" "" | quote }}
            - name: KAFKA_CFG_LOG_SEGMENT_BYTES
              value: {{ .Values.logSegmentBytes | replace "_" "" | quote }}
            - name: KAFKA_CFG_LOG_DIRS
              value: {{ .Values.logsDirs }}
            - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
              value: {{ .Values.defaultReplicationFactor | quote }}
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.offsetsTopicReplicationFactor | quote }}
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: {{ .Values.transactionStateLogReplicationFactor | quote }}
            - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: {{ .Values.sslEndpointIdentificationAlgorithm | quote }}
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: {{ .Values.transactionStateLogMinIsr | quote }}
            - name: KAFKA_CFG_NUM_IO_THREADS
              value: {{ .Values.numIoThreads | quote }}
            - name: KAFKA_CFG_NUM_NETWORK_THREADS
              value: {{ .Values.numNetworkThreads | quote }}
            - name: KAFKA_CFG_NUM_PARTITIONS
              value: {{ .Values.numPartitions | quote }}
            - name: KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR
              value: {{ .Values.numRecoveryThreadsPerDataDir | quote }}
            - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
              value: {{ .Values.socketReceiveBufferBytes | quote }}
            - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
              value: {{ .Values.socketRequestMaxBytes | replace "_" "" | quote }}
            - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
              value: {{ .Values.socketSendBufferBytes | quote }}
            - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: {{ .Values.zookeeperConnectionTimeoutMs | quote }}
            {{- if .Values.extraEnvVars }}
            {{ include "kafka.tplValue" ( dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - name: kafka
              containerPort: {{ .Values.service.port }}
            {{- if .Values.auth.ssl }}
            - name: kafka-ssl
              containerPort: 9093
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /bitnami/kafka
            {{- end }}
            {{- if .Values.config }}
            - name: kafka-config
              mountPath: /opt/bitnami/kafka/conf/server.properties
              subPath: server.properties
            {{- end }}
            {{- if or .Values.auth.enabled .Values.auth.ssl }}
            - name: kafka-certificates
              mountPath: /opt/bitnami/kafka/conf/certs/
              readOnly: true
            {{- end }}
        {{ if .Values.metrics.jmx.enabled }}
        - name: jmx-exporter
          image: "{{ template "kafka.metrics.jmx.image" . }}"
          imagePullPolicy: "{{ .Values.metrics.jmx.image.pullPolicy }}"
          command:
            - java
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+UseCGroupMemoryLimitForHeap
            - -XX:MaxRAMFraction=1
            - -XshowSettings:vm
            - -jar
            - jmx_prometheus_httpserver.jar
            - {{ .Values.metrics.jmx.exporterPort | quote }}
            - /etc/jmx-kafka/jmx-kafka-prometheus.yml
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.jmx.exporterPort }}
          {{- if .Values.metrics.jmx.resources }}
          resources: {{ toYaml .Values.metrics.jmx.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-kafka
        {{ end }}
      volumes:
        {{ if .Values.metrics.jmx.enabled }}
        - name: jmx-config
          configMap:
            {{- if .Values.metrics.jmx.configMap.overrideName }}
            name: {{ .Values.metrics.jmx.configMap.overrideName }}
            {{- else }}
            name: {{ template "kafka.fullname" . }}-jmx-configuration
            {{- end }}
        {{ end }}
        {{ if .Values.config }}
        - name: kafka-config
          configMap:
            name: {{ template "kafka.fullname" . }}-configuration
        {{ end }}
        {{ if or .Values.auth.enabled .Values.auth.ssl }}
        - name: kafka-certificates
          secret:
            secretName: {{ required "A secret containing the Kafka JKS certificates is required when authentication in enabled" .Values.auth.certificatesSecret }}
            defaultMode: 256
        {{ end }}
{{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "kafka.storageClass" . | nindent 8 }}
{{- end }}
