[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.build-data-collector]
dependencies = [
    "clippy",
	"test",
	"build",
]

[tasks.build-data-collector-docker]
dependencies = [
	"musl-build",
	"build-data-collector-docker-image",
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target",
	"docker run --rm -v $PWD:/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry ekidd/rust-musl-builder:stable-openssl11 cargo build --release"
]

[tasks.build-data-collector-docker-image]
command = "docker"
args = ["build", "-t", "kiln/data-collector:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-data-collector-master-docker]
dependencies = ["musl-build", "build-data-collector-docker-tag-master-version", "build-data-collector-docker-tag-master-latest"]

[tasks.build-data-collector-docker-tag-master-version]
command = "docker"
args = ["build", "-t", "kiln/data-collector:master-${GIT_SHA}", "."]

[tasks.push-data-collector-docker-master-version]
command = "docker"
args = ["push", "kiln/data-collector:master-${GIT_SHA}"]

[tasks.build-data-collector-docker-tag-master-latest]
command = "docker"
args = ["tag", "kiln/data-collector:master-${GIT_SHA}", "kiln/data-collector:master-latest"]

[tasks.push-data-collector-docker-master-latest]
command = "docker"
args = ["push", "kiln/data-collector:master-latest"]

[tasks.build-data-collector-release-docker]
dependencies = ["musl-build", "build-data-collector-docker-tag-release-version", "build-data-collector-docker-tag-release-latest"]

[tasks.build-data-collector-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/data-collector:$GIT_TAG ."
]

[tasks.push-data-collector-docker-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/data-collector:$GIT_TAG ."
]

[tasks.build-data-collector-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/data-collector:$GIT_TAG kiln/data-collector:latest"
]

[tasks.push-data-collector-docker-release-latest]
script = [
	"docker push kiln/data-collector:latest"
]
