[env]
GIT_SHA = { script = ["git rev-parse --short HEAD"] }
GIT_BRANCH = { script = ["git rev-parse --abbrev-ref HEAD"] }

[tasks.build-data-collector]
dependencies = [
    "clippy",
	"test",
	"build",
]

[tasks.build-data-collector-docker]
dependencies = [
	"musl-build",
	"build-data-collector-docker-image",
]

[tasks.musl-build]
script = [
	"mkdir target &> /dev/null || true",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable sudo chown -R rust:rust /opt/rust/cargo/git /opt/rust/cargo/registry /home/rust/src/target",
	"docker run --rm -e CARGO_HOME=/opt/rust/cargo -v $PWD:/home/rust/src -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/git:/opt/rust/cargo/git -v ${XDG_CACHE_HOME:-$HOME/.cache}/docker/cargo/registry:/opt/rust/cargo/registry ekidd/rust-musl-builder:stable cargo build --release"
]

[tasks.build-data-collector-docker-image]
command = "docker"
args = ["build", "-t", "kiln/data-collector:${GIT_BRANCH}-${GIT_SHA}", "."]

[tasks.build-data-collector-git-docker]
dependencies = ["musl-build", "build-data-collector-docker-tag-git-version", "build-data-collector-docker-tag-git-latest"]

[tasks.build-data-collector-docker-tag-git-version]
command = "docker"
args = ["build", "-t", "kiln/data-collector:git-${GIT_SHA}", "."]

[tasks.push-data-collector-docker-git-version]
command = "docker"
args = ["push", "kiln/data-collector:git-${GIT_SHA}"]

[tasks.build-data-collector-docker-tag-git-latest]
command = "docker"
args = ["tag", "kiln/data-collector:git-${GIT_SHA}", "kiln/data-collector:git-latest"]

[tasks.push-data-collector-docker-git-latest]
command = "docker"
args = ["push", "kiln/data-collector:git-latest"]

[tasks.build-data-collector-release-docker]
dependencies = ["musl-build", "build-data-collector-docker-tag-release-version", "build-data-collector-docker-tag-release-latest"]

[tasks.build-data-collector-docker-tag-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker build -t kiln/data-collector:$GIT_TAG ."
]

[tasks.push-data-collector-docker-release-version]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker push kiln/data-collector:$GIT_TAG ."
]

[tasks.build-data-collector-docker-tag-release-latest]
script = [
	"GIT_TAG=git rev-parse --abbrev-ref HEAD",
	"docker tag kiln/data-collector:$GIT_TAG kiln/data-collector:latest"
]

[tasks.push-data-collector-docker-release-latest]
script = [
	"docker push kiln/data-collector:latest"
]
