service: data-collector
tags: ${self:custom.tags}

provider:
  name: aws
  region: ${self:custom.region}
  runtime: rust
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  stackTags: ${self:custom.tags}
  vpc:
    securityGroupIds: ${self:custom.securityGroupIds}
    subnetIds: ${self:custom.subnetIds}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
      Resource: '*'

package:
  individually: true

plugins:
  - serverless-rust

functions:
  data-collector:
    handler: data-collector 
    events:
      - http:
          path: '/'
          method: GET

custom: ${file(config/${self:provider.stage}.yml)}
