name: Build Git Docker Images
on:
    push:
        branches:
            - main 

jobs:
    data-collector:
        name: Data-collector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v2.1.5
              with:
                path: data-collector/target
                key: ${{ runner.os }}-cargo-build-target-musl-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Build
              run: cargo make build-data-collector-git-docker
              working-directory: data-collector/
            - name: docker login
              uses: azure/docker-login@v1
              with:
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                username: kilnautomation
            - name: Docker push version
              run: cargo make push-data-collector-docker-git-version
              working-directory: data-collector/
            - name: Docker push latest
              run: cargo make push-data-collector-docker-git-latest
              working-directory: data-collector/
    data-forwarder:
        name: Data-forwarder build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v2.1.5
              with:
                path: data-forwarder/target
                key: ${{ runner.os }}-cargo-build-target-musl-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Build data-forwarder
              run: cargo make build-data-forwarder-musl
              working-directory: data-forwarder/
            - name: Upload data-forwarder
              uses: actions/upload-artifact@v2.2.4
              with:
                name: data-forwarder
                path: bin/data-forwarder
    build-bundler-audit-docker:
        name: Build Bundler-Audit tool docker image
        runs-on: ubuntu-18.04
        needs: data-forwarder
        steps:
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: Download pre-built data-forwarder
              uses: actions/download-artifact@v2.0.9
              with:
                name: data-forwarder
                path: tool-images/ruby/bundler-audit/
            - name: Build bundler-audit
              run: cargo make build-bundler-audit-git-docker
              working-directory: tool-images/ruby/bundler-audit
            - name: docker login
              uses: azure/docker-login@v1
              with:
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                username: kilnautomation
            - name: Docker push version
              run: cargo make bundler-audit-docker-push-git-version
              working-directory: tool-images/ruby/bundler-audit
            - name: Docker push latest
              run: cargo make bundler-audit-docker-push-git-latest
              working-directory: tool-images/ruby/bundler-audit
    build-safety-docker:
        name: Build Safety tool docker image
        runs-on: ubuntu-18.04
        needs: data-forwarder
        steps:
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: Download pre-built data-forwarder
              uses: actions/download-artifact@v2.0.9
              with:
                name: data-forwarder
                path: tool-images/python/safety/
            - name: Build safety
              run: cargo make build-safety-git-docker
              working-directory: tool-images/python/safety
            - name: docker login
              uses: azure/docker-login@v1
              with:
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                username: kilnautomation
            - name: Docker push version
              run: cargo make safety-docker-push-git-version
              working-directory: tool-images/python/safety
            - name: Docker push latest
              run: cargo make safety-docker-push-git-latest
              working-directory: tool-images/python/safety
    report-parser:
        name: Report-parser build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v2.1.5
              with:
                path: report-parser/target
                key: ${{ runner.os }}-cargo-build-target-musl-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Build
              run: cargo make build-report-parser-git-docker
              working-directory: report-parser/
            - name: docker login
              uses: azure/docker-login@v1
              with:
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                username: kilnautomation
            - name: Docker push version
              run: cargo make push-report-parser-docker-git-version
              working-directory: report-parser/
            - name: Docker push latest
              run: cargo make push-report-parser-docker-git-latest
              working-directory: report-parser/
    slack-connector:
        name: Slack-connector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v2.1.5
              with:
                path: ~/.cache/docker/cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v2.1.5
              with:
                path: slack-connector/target
                key: ${{ runner.os }}-cargo-build-target-musl-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Build
              run: cargo make build-slack-connector-git-docker
              working-directory: slack-connector/
            - name: docker login
              uses: azure/docker-login@v1
              with:
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                username: kilnautomation
            - name: Docker push version
              run: cargo make push-slack-connector-docker-git-version
              working-directory: slack-connector/
            - name: Docker push latest
              run: cargo make push-slack-connector-docker-git-latest
              working-directory: slack-connector/
