name: CI
on: [push]

jobs:
    data-collector:
        name: Data-collector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: data-collector/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Build
              run: cargo make build-data-collector
              working-directory: data-collector/
    data-forwarder:
        name: Data-forwarder build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: data-forwarder/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Build data-forwarder
              run: cargo make build-data-forwarder-musl
              working-directory: data-forwarder/
    kiln_lib:
        name: Kiln_lib build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: kiln_lib/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Build
              run: cargo build --all-features
              working-directory: kiln_lib/
            - name: Test
              run: cargo test --all-features
              working-directory: kiln_lib/
            - name: Lint
              run: cargo clippy --all-features
              working-directory: kiln_lib/
    check-cargo-makefile-syntax:
        name: Check cargo Makefile syntax is valid
        runs-on: ubuntu-18.04
        steps:
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - uses: actions/checkout@v1
            - name: Check top-level Makefile
              run: cargo make --print-steps 2>1& > /dev/null
            - name: Check data-collector Makefile
              run: cargo make --print-steps 2>1& > /dev/null
              working-directory: data-collector/
            - name: Check bundler-audit Makefile
              run: cargo make --print-steps 2>&1 > /dev/null
              working-directory: tool-images/ruby/bundler-audit
            - name: Check data-forwarder Makefile
              run: cargo make --print-steps 2>&1 > /dev/null
              working-directory: data-forwarder
