name: CI
on: [push]

jobs:
    build-cargo-workspace:
        name: Cargo workspace build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Build
              run: cargo build
    test-cargo-workspace:
        name: Cargo workspace tests
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Test
              run: cargo test
    lint-cargo-workspace:
        name: Cargo workspace lint
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Lint
              run: cargo clippy
