name: CI
on: [push]

jobs:
    data-collector:
        name: Data-collector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: data-collector/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: data-collector/
            - name: Clippy
              run: cargo clippy
              working-directory: data-collector/
            - name: Build
              run: cargo make build-data-collector
              working-directory: data-collector/
    data-forwarder:
        name: Data-forwarder build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: data-forwarder/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('data-forwarder/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: data-forwarder/
            - name: Clippy
              run: cargo clippy
              working-directory: data-forwarder/
            - name: Build data-forwarder
              run: cargo make build-data-forwarder-musl
              working-directory: data-forwarder/
    kiln-cli:
        name: CLI build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('cli/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('cli/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: cli/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('cli/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: cli/
            - name: Clippy
              run: cargo clippy
              working-directory: cli/
            - name: Test
              run: cargo test
              working-directory: cli/
            - name: Build kiln-cli-tool
              run: cargo make build-kiln-cli
              working-directory: cli/
    report-parser:
        name: Report-parser build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: report-parser/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('report-parser/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: report-parser/
            - name: Clippy
              run: cargo clippy
              working-directory: report-parser/
            - name: Build
              run: cargo make build-report-parser
              working-directory: report-parser/
    slack-connector:
        name: Slack-connector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: slack-connector/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('slack-connector/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: slack-connector/
            - name: Clippy
              run: cargo clippy
              working-directory: slack-connector/
            - name: Build
              run: cargo make build-slack-connector
              working-directory: slack-connector/
    kiln_lib:
        name: Kiln_lib build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: kiln_lib/target
                key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('kiln_lib/Cargo.lock') }}
            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: kiln_lib/
            - name: Lint
              run: cargo clippy --all-features
              working-directory: kiln_lib/
            - name: Build
              run: cargo build --all-features
              working-directory: kiln_lib/
            - name: Test
              run: cargo test --all-features
              working-directory: kiln_lib/
    check-cargo-makefile-syntax:
        name: Check cargo Makefile syntax is valid
        runs-on: ubuntu-18.04
        steps:
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - uses: actions/checkout@v2.3.4
            - name: Check top-level Makefile
              run: cargo make --print-steps 2>1& > /dev/null
            - name: Check data-collector Makefile
              run: cargo make --print-steps 2>1& > /dev/null
              working-directory: data-collector/
            - name: Check bundler-audit Makefile
              run: cargo make --print-steps 2>&1 > /dev/null
              working-directory: tool-images/ruby/bundler-audit
            - name: Check data-forwarder Makefile
              run: cargo make --print-steps 2>&1 > /dev/null
              working-directory: data-forwarder
