name: CI
on: [push]

jobs:
    data-collector:
        name: Data-collector CI
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-data-collector-cargo-registry-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-data-collector-cargo-index-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: target
                key: ${{ runner.os }}-data-collector-cargo-build-target-${{ hashFiles('data-collector/Cargo.lock') }}
            - name: Build
              run: cargo build
              working-directory: data-collector/
            - name: Test
              run: cargo test
              working-directory: data-collector/
            - name: Lint
              run: cargo clippy
              working-directory: data-collector/
    kiln_lib:
        name: Kiln_lib CI 
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-kiln-lib-cargo-registry-${{ hashFiles('kiln_lib/Cargo.lock') }}
              working-directory: kiln_lib/
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                path: ~/.cargo/git
                key: ${{ runner.os }}-kiln-lib-cargo-index-${{ hashFiles('kiln_lib/Cargo.lock') }}
              working-directory: kiln_lib/
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                path: target
                key: ${{ runner.os }}-kiln-lib-cargo-build-target-${{ hashFiles('kiln_lib/Cargo.lock') }}
              working-directory: kiln_lib/
            - name: Build
              run: cargo build
              working-directory: kiln_lib/
            - name: Test
              run: cargo test
              working-directory: kiln_lib/
            - name: Lint
              run: cargo clippy
              working-directory: kiln_lib/
    check-cargo-makefile-syntax:
        name: Check cargo Makefile syntax is valid
        runs-on: ubuntu-18.04
        steps:
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - uses: actions/checkout@v1
            - name: Check top-level Makefile
              run: cargo make --print-steps 2>1& > /dev/null
            - name: Check data-collector Makefile
              run: cargo make --print-steps 2>1& > /dev/null
              working-directory: data-collector/
