name: CI
on: [push]

jobs:
    build-data-collector:
        name: Data-collector build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Build
              run: cargo build
              working-directory: data-collector/
    test-data-collector:
        name: Data-collector tests
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Test
              run: cargo test
              working-directory: data-collector/
    lint-data-collector:
        name: Data-collector lint
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Lint
              run: cargo clippy
              working-directory: data-collector/
    build-kiln_lib:
        name: Kiln_lib build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Build
              run: cargo build
              working-directory: kiln_lib/
    test-kiln-lib:
        name: Kiln_lib tests
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Test
              run: cargo test
              working-directory: kiln_lib/
    lint-kiln-lib:
        name: Kiln_lib lint
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Lint
              run: cargo clippy
              working-directory: kiln_lib/
    check-cargo-makefile-syntax:
        name: Check cargo Makefile syntax is valid
        runs-on: ubuntu-18.04
        steps:
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - uses: davidB/rust-cargo-make@v1
              with:
                version: 0.22.2
            - uses: actions/checkout@v1
            - name: Check top-level Makefile
              run: cargo make --print-steps 2&>1 > /dev/null
            - name: Check data-collector Makefile
              run: cargo make --print-steps 2&>1 > /dev/null
              working-directory: data-collector/
